/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wind_ndk_opengles_n_NativeGLRenderer */

#ifndef _Included_com_wind_ndk_opengles_n_NativeGLRenderer
#define _Included_com_wind_ndk_opengles_n_NativeGLRenderer
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wind_ndk_opengles_n_NativeGLRenderer
 * Method:    native_on_surface_created
 * Signature: (Ljava/lang/Object;)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_opengles_n_NativeGLRenderer_native_1on_1surface_1created
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_wind_ndk_opengles_n_NativeGLRenderer
 * Method:    native_on_surface_changed
 * Signature: (Ljava/lang/Object;II)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_opengles_n_NativeGLRenderer_native_1on_1surface_1changed
  (JNIEnv *, jobject, jobject, jint, jint);

/*
 * Class:     com_wind_ndk_opengles_n_NativeGLRenderer
 * Method:    native_on_surface_destroy
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_opengles_n_NativeGLRenderer_native_1on_1surface_1destroy
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_opengles_n_NativeGLRenderer
 * Method:    native_init
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_opengles_n_NativeGLRenderer_native_1init
  (JNIEnv *, jobject);

/*
 * Class:     com_wind_ndk_opengles_n_NativeGLRenderer
 * Method:    native_update_tex_image
 * Signature: ([BII)V
 */
JNIEXPORT void JNICALL Java_com_wind_ndk_opengles_n_NativeGLRenderer_native_1update_1tex_1image
  (JNIEnv *, jobject, jobject jbitmap);

#ifdef __cplusplus
}
#endif
#endif
